Renders the countdown block in php for FSE
amnestywebsite/humanity-theme pull request #152
Opened 2024-04-11 11:16 UTC by Gentyspun

Ref: https://github.com/amnestywebsite/humanity-theme/issues/148

Reworks the countdown timer to be rendered in PHP to bring in line with FSE

**Steps to test**:
1. Edit a post
2. Countdown timer should be show in the block inserter
3. Add the block, populate and save
4. View the front end and make sure the block displays as expected

Example: http://bigbite.im/i/5f672I

2024-04-18 14:40 UTC, jaymcp submitted a review, later dismissed
This needs a deprecation, so that old versions of the blocks can be transformed without breaking.

2024-04-23 14:01 UTC, jaymcp requested changes
Thanks for addressing the feedback. Sorry to kick this back again, but now that the deprecation's working, I can see the output of the PHP render, and I'm seeing PHP Warnings. I've left a suggested fix inline.

2024-04-23 14:01 UTC, jaymcp commented on wp-content/themes/humanity-theme/includes/blocks/countdown-timer/render.php
> +		);
```suggestion
	 * @return string
	 */
	function amnesty_render_countdown_block( array $attrs = [] ): string {
		$attrs = wp_parse_args(
			$attrs,
			[
				'alignment'   => 'inherit',
				'date'        => '',
				'expiredText' => '',
			]
		);

		return sprintf(
			'<div class="clockdiv" style="text-align:%s;">
				<div class="countdownClock" data-timestamp="%s" data-expiredText="%s"></div>
			</div>',
			esc_attr( $attrs['alignment'] ),
			esc_attr( $attrs['date'] ),
			esc_attr( $attrs['expiredText'] )
		);
```

2024-04-25 14:19 UTC, Gentyspun commented on wp-content/themes/humanity-theme/includes/blocks/countdown-timer/render.php
> +		);
resolved

2024-04-30 12:53 UTC, jaymcp approved these changes
Thanks for the work on this!

2024-04-30 14:00 UTC, merged