Call to Action FSE Support
amnestywebsite/humanity-theme pull request #155
Opened 2024-04-15 08:02 UTC by Gentyspun

Ref: https://github.com/amnestywebsite/humanity-theme/issues/142

**Steps to test**:
1. Edit a post, the Call to Action block should now appear in the block inserter
2. Add a CTA block and populate with content
3. Save and view the front end.
4. CTA should display as expected

Example: http://bigbite.im/i/wR98Yf

2024-04-18 15:09 UTC, jaymcp requested changes
This needs a deprecation, so that old versions of the blocks can be transformed without breaking.

2024-04-18 15:09 UTC, jaymcp commented on wp-content/themes/humanity-theme/includes/blocks/call-to-action/render.php
> +		$cta_content = isset( $attrs['content'] ) ? $attrs['content'] : '';
```suggestion
		$attrs = wp_parse_args(
			[
				'preheading' => '',
				'title'      => '',
				'content'    => '',
			],
			$attrs,
		);

		$pre_heading = $attrs['preheading'];
		$heading     = $attrs['title'];
		$cta_content = $attrs['content'];
```

2024-04-23 10:46 UTC, Gentyspun commented on wp-content/themes/humanity-theme/includes/blocks/call-to-action/render.php
> +		$cta_content = isset( $attrs['content'] ) ? $attrs['content'] : '';
resolved

2024-04-23 10:48 UTC, Gentyspun commented on wp-content/themes/humanity-theme/includes/blocks/call-to-action/render.php
> +	 * @return string|null
resolved

2024-04-23 10:56 UTC, Gentyspun commented on wp-content/themes/humanity-theme/includes/blocks/call-to-action/render.php
> +			wp_kses_post( $content )
resolved

2024-04-23 14:34 UTC, jaymcp submitted a review, later dismissed
in `blocks/call-to-action/index.jsx`, the `classnames` import is no longer required, nor are `isEmpty` and `RichText`.

i'm not sure what's causing the issue, but the CTA doesn't render correctly with this change. 

1. i had an existing page containing CTA blocks, which converted fine, but have issues in the render due to a line break in the `aria-label` on the container. the background and demarcation lines are also missing:
![](http://bigbite.im/i/fYZAeH+)
2. i inserted new CTA blocks on a new page, and i only see the buttons being output:
![](http://bigbite.im/i/XD0b2L+)

2024-04-23 14:34 UTC, jaymcp commented on wp-content/themes/humanity-theme/includes/blocks/call-to-action/render.php
> +	 * @param string $content    the block content
```suggestion
	 * @param array  $attrs   the block attributes
	 * @param string $content the block content
```

2024-04-25 14:48 UTC, Gentyspun commented on wp-content/themes/humanity-theme/includes/blocks/call-to-action/render.php
> +	 * Render a download block
resolved

2024-04-25 14:48 UTC, Gentyspun commented on wp-content/themes/humanity-theme/includes/blocks/call-to-action/render.php
> +	 * @param string $content    the block content
resolved

2024-04-25 15:11 UTC, Gentyspun commented on private/src/scripts/editor/blocks/call-to-action/deprecated.jsx
> +  },
Yep, resolved

2024-04-30 12:58 UTC, jaymcp approved these changes
Great! thanks for the PR, and for addressing the feedback!

2024-04-30 14:00 UTC, merged