Register and render the counter block in PHP
amnestywebsite/humanity-theme pull request #157
Opened 2024-04-16 18:38 UTC by Gentyspun

Ref: [#145](https://github.com/amnestywebsite/humanity-theme/issues/145)

**Steps to test**:
1.  Edit a post
2. Check if counter block appears in the block inserter
3. Add the block and content
4. Save and view the front end
5. Check block functions as expected

Example: http://bigbite.im/i/kn8U03

2024-04-18 14:46 UTC, jaymcp requested changes
I'm not sure the deprecation is functioning correctly:
![](http://bigbite.im/i/OdVAIg+)

2024-04-18 14:46 UTC, jaymcp commented on wp-content/themes/humanity-theme/includes/blocks/stat-counter/register.php
> +				'render_callback' => 'render_stat_counter_block',
```suggestion
				'editor_script'   => 'amnesty-stat-counter-block-editor',
				'render_callback' => 'render_stat_counter_block',
```

2024-04-18 14:46 UTC, jaymcp commented on wp-content/themes/humanity-theme/includes/blocks/stat-counter/register.php
> +	function register_stat_counter_block() {
```suggestion
	function register_stat_counter_block(): void {
```

2024-04-18 14:46 UTC, jaymcp commented on wp-content/themes/humanity-theme/includes/blocks/stat-counter/register.php
> +	 * @package Amnesty/Blocks
```suggestion
	 * @package Amnesty\Blocks
```

2024-04-18 14:46 UTC, jaymcp commented on wp-content/themes/humanity-theme/includes/blocks/stat-counter/render.php
> +	 * @package Amnesty/Blocks
```suggestion
	 * @package Amnesty\Blocks
```

2024-04-18 14:46 UTC, jaymcp commented on wp-content/themes/humanity-theme/includes/blocks/stat-counter/render.php
> +		$value = $attributes['value'] ?? '';
```suggestion
		$attributes = wp_parse_args(
			[
				'alignment' => '',
				'duration'  => 2,
				'value'     => 0,
			],
			$attributes,
		);

		$alignment = 'align' . $attributes['alignment'];
		$duration  = $attributes['duration'];
		$value     = $attributes['value'];
```

2024-04-18 14:46 UTC, jaymcp commented on wp-content/themes/humanity-theme/includes/blocks/stat-counter/render.php
> +				'class' => $alignment
```suggestion
				'class' => $alignment,
```

2024-04-23 11:20 UTC, Gentyspun commented on wp-content/themes/humanity-theme/includes/blocks/stat-counter/register.php
> +				'render_callback' => 'render_stat_counter_block',
resolved

2024-04-23 11:21 UTC, Gentyspun commented on wp-content/themes/humanity-theme/includes/blocks/stat-counter/register.php
> +	 * @package Amnesty/Blocks
resolved

2024-04-23 11:22 UTC, Gentyspun commented on wp-content/themes/humanity-theme/includes/blocks/stat-counter/render.php
> +		$value = $attributes['value'] ?? '';
resolved

2024-04-23 11:22 UTC, Gentyspun commented on wp-content/themes/humanity-theme/includes/blocks/stat-counter/render.php
> +				'class' => $alignment
resolved

2024-04-23 11:26 UTC, Gentyspun commented on wp-content/themes/humanity-theme/includes/blocks/stat-counter/register.php
> +	function register_stat_counter_block() {
resolved

2024-04-23 14:20 UTC, merged